### ISSUE TITLE
TLitte issues

### ISSUE THREAD

**Issue by yinbingge** [nationalparkservice/NSNSDAcoustics#10]
I downloaded the source codes and released it to my local computer. I followed all the instruction and got this error. Please let me know if you need any more information.

Thanks
------------------
Error: Cannot analyze audio file 
C:/Users/xxxx/Documents/example-audio-directory/Rivendell_20210623_113602.wav.
Traceback (most recent call last):
  File "<string>", line 268, in analyzeFile
  File "<string>", line 217, in predict
  File "C:\Program Files\BirdNET-Analyzer-main\model.py", line 121, in predict
    loadModel()
  File "C:\Program Files\BirdNET-Analyzer-main\model.py", line 38, in loadModel
    INTERPRETER = tflite.Interpreter(model_path=cfg.MODEL_PATH, num_threads=cfg.TFLITE_THREADS)
  File "C:\PROGRA~3\ANACON~1\envs\PYBIRD~1\lib\site-packages\tensorflow\lite\python\interpreter.py", line 197, in __init__
    _interpreter_wrapper.CreateWrapperFromFile(
ValueError: Op builtin_code out of range: 127. Are you using old TFLite binary with newer model?Registration failed

![image](https://user-images.githubusercontent.com/30634599/200372350-8eefa860-5e0b-47b1-9516-354acb5b1e4b.png)

**Comment by cbalantic** [comment]
Thank you! Should now be fixed. https://github.com/nationalparkservice/NSNSDAcoustics/commit/7d05a35355fef54685492468d5d950c9266b9e6d
